import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import './Welcome.css';
import End from './End';

const Welcome = () => {
  const navigator = useNavigate();

  

  return (
    <div className='block'> 
      <div>
        <End></End>
      </div>
      <div className='Head' style={{textAlign:'center'}}>
        <h1 >Welcome to the 2Face</h1>
      </div>

      <div className='rule'>
       
        <Card style={{ width: '50rem' }}>
          <Card.Body >
            <Card.Title style={{fontSize:'2em',marginTop:'20px'}}>Face authentication</Card.Title>
            <Card.Text style={{fontSize:'1.5em'}}>
            <p>Each User has a model that generated by the face features </p>
            <p>We use facial recognition to authenticate users to the platform </p>
            </Card.Text>
            <Button 
              variant="primary"
              id ='playButton'
              onClick={()=>{navigator('/capture')}}>
              Try!</Button>

              <Card.Title style={{fontSize:'2em',marginTop:'50px'}}>Peer facetime</Card.Title>
              <Card.Text style={{fontSize:'1.5em'}}>
            <p>User can copy their ID and send to their friend</p>
            <p>Use ID to call and initate a channel to talk </p>
            </Card.Text>
            <Button 
              variant="primary"
              id ='playButton'
              onClick={()=>{navigator('/video')}}>
              Try!</Button>
          </Card.Body>
        </Card>        
      </div>

      
    </div>
  );
}

export default Welcome;